version: "3.8"

services:
  backend:
    build:
      context: ./rtcc-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    networks:
      - collab-net

  frontend:
    build:
      context: ./rtcc-client
      dockerfile: Dockerfile

    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_WEBSOCKET_URL=ws://backend:8080/ws
    depends_on:
      - backend
    networks:
      - collab-net

networks:
  collab-net:
    driver: bridge
